// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:commitlock/models/session_model.dart';
import 'package:commitlock/models/streak_model.dart';
import 'package:commitlock/models/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SessionModelAdapter());
    registerAdapter(StreakModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SessionModelAdapter());
    registerAdapter(StreakModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
